### ISSUE TITLE
panicked at 'byte index 76 is not a char boundary

### ISSUE THREAD

**Issue by rubymix** [hummingly/ics#15]
Hello, there.
I have a issue with next_boundary function.
Could you please fix this issue?

For exmaple, change 71 line in contentline.rs
` let content = "Content lines shouldn't be folded in the middle of a UTF-8 character! 老虎.";`
to
` let content = "Content lines shouldn't be folded in the middle of a UTF-8 character! 老 虎.";`

and cargo test
```
---- contentline::tests::multibytes stdout ----
thread 'contentline::tests::multibytes' panicked at 'byte index 76 is not a char boundary; it is inside '虎' (bytes 74..77) of `Content lines shouldn't be folded in the middle of a UTF-8 character! 老 虎.`', src/contentline.rs:30:11
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by hummingly** [comment]
I made a mistake by indexing into the string and not into the bytes.

I'm very sorry that I am replying so late. My notifications were set to the minimum :( I changed it to watching the respository but if something is urgent, just ping me.
